### ISSUE TITLE
NMAP scan options

### ISSUE THREAD

**Issue by CCOSTAN** [eximo84/homeassistant-config#10]
Noticed that you have enabled scan options on your nmap config. Any reason?

**Comment by eximo84** [comment]
By default nmap doesn't detect Windows 10 devices as online.  I tried a few different options and this setup seems to work out best for me.

I actually don't know which device tracker works out best between nmap and ASUSWRT - having both hasn't caused me any major problems and my devices are tracked pretty well with this setup.

**Comment by eximo84** [comment]
Removed NMAP device tracker - tested with ASUSWRT only and device tracking remains the same as before.
